name: build_test_push_stopgap_predictmd
on:
  pull_request:
  push:
    branches:
      - master
      - staging
      - trying
jobs:
  build_test_push_stopgap_predictmd:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version:
          - '1'
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
      - run: julia --project -e 'using SimpleContainerGenerator; pkgs = [(name = "PredictMD", rev = "master"), (name = "PredictMDExtra", rev = "master"), (name = "PredictMDFull", rev = "master")]; stopgap_docker(pkgs; julia_version = "nightly")'
      - if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - run: docker build -t dilumaluthge/stopgap_predictmd .
      - run: docker run dilumaluthge/stopgap_predictmd "JULIA_DEBUG=all PREDICTMD_TEST_GROUP=all PREDICTMD_TEST_PLOTS=true /usr/bin/stopgap_julia -e 'import Pkg; Pkg.test(string(:PredictMDExtra)); Pkg.test(string(:PredictMDFull)); Pkg.test(string(:PredictMD))'"
      - if: success() && github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: docker push dilumaluthge/stopgap_predictmd
